### ISSUE TITLE
TypeError: Type str doesn't support the buffer API

### ISSUE THREAD

**Issue by larseggert** [GeeF/SublimeDiction#2]
Keep getting these:
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "diction in /Users/lars/Library/Application Support/Sublime Text 3/Installed Packages/Diction.sublime-package", line 229, in run
  File "diction in /Users/lars/Library/Application Support/Sublime Text 3/Installed Packages/Diction.sublime-package", line 160, in mark_words
  File "diction in /Users/lars/Library/Application Support/Sublime Text 3/Installed Packages/Diction.sublime-package", line 75, in run_diction
TypeError: Type str doesn't support the buffer API
```

**Comment by GeeF** [comment]
Hey, thanks for digging this up again :)
It should already be updatable via package control.
